<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="container">
    
<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="next"><?php echo $this->tag->linkTo(["product/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Lista de productos</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Created</th>
            <th>Updated</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $product): ?>
            <tr>
                <td><?php echo $product->getId() ?></td>
            <td><?php echo $product->getName() ?></td>
            <td><?php echo $product->getDescription() ?></td>
            <td title="<?= date("Y-m-d h:i:sa", $product->getCreatedAt()) ?>"><?= date("d/m/Y", $product->getCreatedAt()) ?></td>
            <td title="<?= date("Y-m-d h:i:sa", $product->getUpdatedAt() ) ?>"><?= date("d/m/Y", $product->getUpdatedAt() ) ?></td>
                <?php  $id = str_replace(array("'",'%'),array('%27',"'"),urlencode($this->crypt->encryptBase64($product->getId()))); ?>
                <td><?php echo $this->tag->linkTo(["product/edit/" . $id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["product/delete/" . $id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("product/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("product/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("product/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("product/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
</div>
