<div class="px-5">
    <div class="row">
        <div class="col-md-6">
            <div>
                
                <img style="width: 700px;" src="<?php echo $this->url->get('/public/img/bg.png')?>" alt="">
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2 class="text-center text-muted">Login</h2>

                </div>
                <div class="card-body">
                    <p><?php echo $this->flashSession->output() ?></p>

                    <?php echo $this->tag->form("user/login/submit"); ?>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <?php echo $form->render('email'); ?>
                        </div>

                        <div class="form-group">
                            <label for="password">Password</label>
                            <?php echo $form->render('password'); ?>
                        </div>

                        <div class="form-group">
                            <?php echo $form->render('submit'); ?>
                        </div>
                        
                        <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>
                    </form>
                    <p>Registrate
                        <?= $this->tag->linkTo('user/register', 'Aquí?') ?>
                    </p>
                </div>

            </div>
        </div>
    </div>

</div>