<div class="px-5">

<div class="row">
    <div class="col-md-6">
        <div>
                    
            <img style="width: 700px;" src="<?php echo $this->url->get('/public/img/bg.png')?>" alt="">
        </div>
    </div>
    <div class="col-md-6">
            <div class="card">
                <div class="card-header"><h2 class="text-center text-muted">Registrate</h2></div>
                <div class="card-body">
                <p><?php echo $this->flashSession->output() ?></p>

                    <?php echo $this->tag->form("user/register/submit"); ?>

                        <div class="form-group">
                            <label for="name">Nombres Completos</label>
                            <?php echo $form->render('name'); ?>
                        </div>

                        <div class="form-group">
                            <label for="email">Email</label>
                            <?php echo $form->render('email'); ?>
                        </div>

                        <div class="form-group">
                            <label for="password">Password</label>
                            <?php echo $form->render('password'); ?>
                        </div>

                        <div class="form-group">
                            <label for="password_confirm">Comfirmar Password</label>
                            <?php echo $form->render('password_confirm'); ?>
                        </div>

                        <div class="form-group">
                            <?php echo $form->render('submit'); ?>
                        </div>

                    </form>
                </div>
            </div>
    </div>
</div>
</div>